import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export default async function handler(req, res) {
  const { text, voice = 'Puck' } = req.query;

  if (!text) {
    return res.status(400).json({ error: 'Text is required' });
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Read the following text naturally aloud. If there are English terms mixed with Burmese, pronounce both correctly in context:\n\n${text}`,
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: voice // AOEDE, CHARON, FENRIR, KORE, PUCK စသဖြင့် ရွေးနိုင်သည်
            }
          }
        }
      }
    });

    const candidate = response.candidates?.[0];
    const part = candidate?.content?.parts?.find(p => p.inlineData && p.inlineData.mimeType?.startsWith('audio/'));

    if (!part) {
      return res.status(500).json({ error: 'No audio generated by Gemini' });
    }

    const audioBuffer = Buffer.from(part.inlineData.data, 'base64');

    res.setHeader('Content-Type', part.inlineData.mimeType || 'audio/wav');
    res.setHeader('Content-Disposition', 'inline; filename="gemini-speech.wav"');
    return res.send(audioBuffer);

  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
}
